### ISSUE TITLE
use w3c app manifest

### ISSUE THREAD

**Issue by bufferoverflow** [max-wittig/close-all-tabs#1]
- https://github.com/w3c/manifest
- https://www.w3.org/TR/appmanifest/
- https://www.chromestatus.com/feature/6488656873259008

**Comment by max-wittig** [comment]
Maybe I missed something, but this is the required manifest for chrome extensions. I can't just use another one?

**Comment by max-wittig** [comment]
Also some web-extension features are slightly different. Maybe this will be a thing in the future. For now it's just a `Working draft or equivalent`

**Comment by bufferoverflow** [comment]
you can deploy to pages provide meta data to the html file and then do an install.

**Comment by bufferoverflow** [comment]
I'll show you tomorrow what I did a while ago with earlier versions of web app manifest.

**Comment by bufferoverflow** [comment]
It was this https://github.com/bufferoverflow/clock/blob/master/manifest.webapp
maybe it is installable via browser then http://bufferoverflow.github.io/clock/ it was possible via mozilla store few years ago

**Comment by max-wittig** [comment]
Yeah it's not a webapp. It's a web-extension in Chrome flavor. https://developer.chrome.com/extensions
